name: Tag incrementation

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag
        run: |  
          #export GITHUB_TAG=$(git describe --abbrev=0 --tags)
          export GITHUB_TAG=$(git describe --tags)
          echo $GITHUB_TAG
          export MAJOR_VERSION=$(echo $GITHUB_TAG | grep -Eo '^[0-9]+')
          echo $MAJOR_VERSION
          echo "major_version=$MAJOR_VERSION" >> $GITHUB_ENV
          export MINOR_VERSION=$(echo $GITHUB_TAG | grep -Eo '\.[0-9]+\.' | grep -Eo '[0-9]+')
          echo $MINOR_VERSION
          echo "minor_version=$MINOR_VERSION" >> $GITHUB_ENV
          export FIX=$(echo $GITHUB_TAG | grep -Eo '\.[0-9]+(\-|$)' | grep -Eo '[0-9]+')
          echo $FIX
          echo "fix=$FIX" >> $GITHUB_ENV
      
      - name: Increase PI release number
        if: ${{ github.ref_name	== 'main' }}
        run: |
          export MINOR_VERSION=${{env.minor_version}}
          MINOR_VERSION=$((MINOR_VERSION+1))
          echo $MINOR_VERSION
          echo "minor_version=$MINOR_VERSION" >> $GITHUB_ENV
          
      - name: Increase fix number
        if: ${{ github.ref_name	== 'develop' }}
        run: |
          export FIX= ${{env.fix}}
          FIX=$((FIX+1))
          echo $FIX
          echo "fix=$FIX" >> $GITHUB_ENV
          
      - name: Create new tag
        run: |
          export NEW_TAG="${{env.major_version}}.${{env.minor_version}}.${{env.fix}}"
          echo $NEW_TAG
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          
      - name: Deploy new tag
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -a ${{env.new_tag}} -m "Version ${{env.new_tag}}"
          #$git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/JanBarann/Tag-test.git" --follow-tags
          #$git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/JanBarann/Tag-test.git" --tags     
          git push --follow-tags
          git push --tags
          
          
          
