name: Tag incrementation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: get latest tag
        run: |
          $GITHUB_TAG=$(git describe --tags)
          echo '$GITHUB_TAG'
          $MAJOR_VERSION=$(GITHUB_TAG | grep -e '[^|v]*.')
          echo '$MAJOR_VERSION'
          $MINOR_VERSION=$(GITHUB_TAG | grep -e '.*.')
          echo '$MINOR_VERSION'
          $FIX=$(GITHUB_TAG | grep -e '.*-')
          echo '$FIX'
