name: Tag incrementation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: get latest tag
        run: |
          #echo "GITHUB_TAG=$(git describe --tags)" >>  $GITHUB_ENV
          $GITHUB_TAG=$(git describe --tags)
          $MAJOR_VERSION=$(GITHUB_TAG | grep -e '[^|v]*.')
          $MINOR_VERSION=$(GITHUB_TAG | grep -e '.*.')
          $FIX=$(GITHUB_TAG | grep -e '.*-')
