name: Tag incrementation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: get latest tag
        run: |
          export GITHUB_TAG=$(git describe --tags)
          echo '$GITHUB_TAG'
          export MAJOR_VERSION=$($GITHUB_TAG | grep -e '[^|v]*.')
          echo '$MAJOR_VERSION'
          export MINOR_VERSION=$($GITHUB_TAG | grep -e '.*.')
          echo '$MINOR_VERSION'
          export FIX=$($GITHUB_TAG | grep -e '.*-')
          echo '$FIX'
