name: Tag incrementation

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get latest tag
        run: |  
          #export GITHUB_TAG=$(git describe --abbrev=0 --tags)
          export GITHUB_TAG=$(git describe --tags)
          echo $GITHUB_TAG
          export MAJOR_VERSION=$(echo $GITHUB_TAG | grep -Eo '^[0-9]+')
          echo $MAJOR_VERSION
          export MINOR_VERSION=$(echo $GITHUB_TAG | grep -Eo '\.[0-9]+\.' | grep -Eo '[0-9]+')
          echo $MINOR_VERSION
          export FIX=$(echo $GITHUB_TAG | grep -Eo '\.[0-9]+(\-|$)' | grep -Eo '[0-9]+')
          echo $FIX
      
      - name: Increase PI release number
        if: ${{ github.ref_name	== 'main' }}
        run: |
          MINOR_VERSION=$((MINOR_VERSION+1))
          echo $MINOR_VERSION
          
      - name: Increase fix number
        if: ${{ github.ref_name	== 'develop' }}
        run: |
          FIX=$((FIX+1))
          echo $FIX
          
      - name: Create new tag
        run: |
          export NEW_TAG="$MAJOR_VERSION.$MINOR_VERSION.$FIX"
          echo $NEW_TAG
          
      - name: Deploy new tag
        run: |
          git tag -a $NEW_TAG -m "Version $NEW_TAG"
          $git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/JanBarann/Tag-test.git" --follow-tags
          $git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/JanBarann/Tag-test.git" --tags
          
          
          
